/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package RecipesUI;

import RecipesBL.NewMeasurement;
import Utilities.Globals;
import RecipesBL.Validate;
import java.awt.Color;

/**
 *
 * @author Jerusalem Live
 */
public class AddMeasurement extends javax.swing.JFrame {

    /**
     * Creates new form AddMeasurement
     */
    public AddMeasurement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblAmountG = new javax.swing.JLabel();
        lblHiddenMessage = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        txtAmountG = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblName.setText("Name");

        lblAmountG.setText("Amount");

        btnSubmit.setText("Submit Measurement");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAmountG)
                            .addComponent(lblName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAmountG, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblHiddenMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAmountG, txtName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmountG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmountG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHiddenMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        boolean valid = validateSubmition();
        if (valid) {
            saveData();
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private boolean validateSubmition(){
        String name = this.txtName.getText();
        String amount = this.txtAmountG.getText();
        String errorMsg = "";
        
        if (name == null ||
            name.equals("") ||
            amount == null ||
            amount.equals("")) {
            errorMsg = Globals.CANNOT_BE_NULL;
            this.lblHiddenMessage.setText(errorMsg);
            return false;
        } else if (!Validate.text(name)) {
            errorMsg = Globals.ENTER_TEXT;
            this.lblHiddenMessage.setText(errorMsg);
            this.txtName.setBackground(Color.red);
            this.txtName.setText("");
            return false;
        } else if(!Validate.number(amount)){
            errorMsg = Globals.ENTER_NUM;
            this.lblHiddenMessage.setText(errorMsg);
            this.txtAmountG.setBackground(Color.red);
            this.txtAmountG.setText("");
            this.txtName.setBackground(Color.white);
            return false;
        }
        
        return true;
    }
    
    private void saveData(){
        String name = this.txtName.getText();
        String amount = this.txtAmountG.getText();
        NewMeasurement newMeasurement = new NewMeasurement(name, amount);
        
        if(newMeasurement.save()){
            this.lblHiddenMessage.setText("The entry was saved successfully");
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel lblAmountG;
    private javax.swing.JLabel lblHiddenMessage;
    private javax.swing.JLabel lblName;
    private javax.swing.JTextField txtAmountG;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
